title: Zahra Aminolroaya # your name (or website title) here
logo: "/images/zahraPhoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have experience in solving data-related problems in the domain of AR/VR from the HCI perspective as well as in the field of NLP.
  <br><br>
  <a href="https://www.linkedin.com/in/zahra-aminolroaya-5133b472/" target="_blank">  <span class="iconify-inline" data-icon="logos:logo-linkedin" width="25"></a> 
  <a href="https://stackoverflow.com/users/3283528/zahra-aminolroaya" target="_blank"> <span class="iconify-inline" data-icon="logos:stackoverflow-icon" width="25"></a> 
  <a href="mailto:z.aminolroaya@gmail.com" target="_blank"><span class="iconify-inline" data-icon="logos:google-gmail" width="25"></span></a> 

theme: jekyll-theme-minimal
